version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
      - .:/var/www
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - .:/var/www:rw
    depends_on:
      - php-fpm

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      - PGPASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    volumes:
      - otm-pgsql:/var/lib/postgresql/data
volumes:
  otm-pgsql:
    driver: local